### ISSUE TITLE
v0.2-v0.5 versions have been yanked from crates.io?

### ISSUE THREAD

**Issue by gilescope** [irrustible/async-oneshot#23]
Is there a link to some rational as to why these versions have been yanked?
(Was expecting something in the readme as that still suggests those versions are good)

**Comment by jan-br** [comment]
Hey @jjl,
Just to let you know. A quite big webrtc project called mediasoup uses your library, which now does not seem to compile anymore without caches. I guess they could transition to an alternative, but republishing this crate would be a lot faster I think.
https://github.com/versatica/mediasoup/blob/v3/rust/Cargo.toml

**Comment by jan-br** [comment]
I think your code looks more than just fine, to be honest. I don't see much to criticize.
Sad to hear that you've lost your motivation. Good luck for the future..

Also I've talked with a good friend of mine @Janrupf. He'd love to take over maintenance for this project.

**Comment by Janrupf** [comment]
Hi there, I've looked through the comments and issues so far as well as the pending PR's. From what I gathered the current implementation (that being async-oneshot on main) has a potential race condition which would need to be fixed (and potentially require further investigation of what else might need to be done).

I honestly wouldn't plan on getting async-hatch merged or ready for now, I think this crate does a good job at being a oneshot async channel and thats exactly what we need.

If you are ok with this I'd like to take over maintenance and get this (re)published ASAP so that no further mediasoup projects break.

**Comment by Janrupf** [comment]
Haven't published anything on crates.io yet, I'll make one

**Comment by Janrupf** [comment]
Alright, signed in there with my Github account

**Comment by Janrupf** [comment]
Alright, I'll close this issue now, the following versions have been unyanked:

- 0.5.9
- 0.5.0
- 0.4.2
- 0.4.0

Thats the versions I've identified that other crates depend on.
